### ISSUE TITLE
Uncaught exception could NOT be pinned to a request/response

### ISSUE THREAD

**Issue by shaunc869** [ORESoftware/domain-haven#1]
Hi! read your medium article and I wanted to test this out, I have a simple sample:

```
const haven = require ('domain-haven')
const express = require('express')
const app = express()
console.log(haven);

app.use(haven.default());
const port = 3001



app.get('/', (req, res) => {

	try {
  setTimeout(function () {
    throw new Error('Fail!')
  }, Math.round(Math.random()*100))
} catch (e) {
  console.log('Custom Error: ' + e.message)
}

res.status(200).send("Ok!");

});

app.listen(port, () => console.log(`Example app listening on port ${port}!`))
```

And I am getting the error:

> haven stderr: Uncaught exception could NOT be pinned to a request/response: { Error: Fail!

I am really hoping to use this on our production express app where one crash takes down the whole server and kills all the valid requests waiting behind the one invalid one. Will this work for that use case and can you tell me what's wrong with the above sample if anything in context of your middle-ware?

Thanks a lot!

**Comment by ORESoftware** [comment]
which version of domain-haven do you have installed? can you check in node_modules to see the exact version? `node_modules/domain-haven/package.json`

**Comment by ORESoftware** [comment]
It's because you are sending the response in the same tick:

```js
res.status(200).send("Ok!");
```

if you remove that line, you will get this in the browser:

```
{
"trappedByDomainHavenMiddleware": true,
"error": "Error: Fail!\n    at Timeout._onTimeout (/home/oleg/codes/oresoftware/domain-haven-test/index.js:14:13)\n    at listOnTimeout (timers.js:327:15)\n    at processTimers (timers.js:271:5)"
}
```

you can customize the response if you use auto:false in the options, let me know if you can't figure out how to customize the response. I am gonna to create a patch that will have a better message than "could NOT be pinned" because in this case it could be pinned, it was just that the headers were already written to the response.

**Comment by ORESoftware** [comment]
if you look at the codebase, there's this line:

```js
    res.once('finish', function () {
      resMap.delete(d.havenUuid);
      d.exit();
      d.removeAllListeners();
    });
```

when the response is sent, we delete it from a hash, and if the error is thrown later on, then we can't look up the response. I am hesitant to put timeout (setTimeout) on it.

I just published a new version with a warning if there response has already been sent before the error occurs. Please try version `v0.0.111`.

**Comment by shaunc869** [comment]
First totally awesome response, and you're right the new version just that. So we're running into this on app engine standard right now, we end up having our instances killed off because of a crash in express from something like this.

I think the real example is you have a promise that fails inside without a proper return and this settimeout emulates that. While our goal is to write bug free, error free code, things happen, so the goal is to find a way to catch all errors under all circumstances at the top level and return a 500 error code and not have express crash out throwing away all the other requests behind the failed one waiting to run.

Let me know if I am thinking about this right.

**Comment by ORESoftware** [comment]
sure this package is the right one, the only one I know of. however if an error is thrown after the response has been written to, you cant write to the response, so best thing to do is log something.

**Comment by shaunc869** [comment]
This is really great we'll try this today and see how it works. I am still blown away that no one else has this issue and the only solution are write perfect code. It's pretty crazy from someone coming from Python. Thanks for the help I'll report back.

**Comment by ORESoftware** [comment]
Right I agree, in general people do use domains to handle unexpected errors, but the technique used by this package is particularly good imo.
